plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-sources.js

packageExtensions: {
  "webpack-config-prefabs@*": {
    "dependencies": {
        "tslib": "1.11.1"
    }
  }
}

pnpFallbackMode: all

preferDeferredVersions: true
