enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  webpack-config-prefabs@*:
    dependencies:
      tslib: 1.11.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpFallbackMode: all

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-berry.js
